<?php

$ar = [
    "المساءلة" => [
        "على علم بالمشاكل أو القضايا التي قد تؤثر على المنظمة." ,
        "تحدد أدوار وحقوق ومسؤوليات الموظفين." ,
        "يتحمل المسؤولية عن النتائج" ,
        "يشجع الموظفين على تحديد أهداف صعبة ولكن قابلة للتحقيق." ,
        "يقبل المساءلة عن النتائج" ,
    ] ,
    "الإنجاز" => [
        "تقبل النكسات والتحديات كفرص للتحسين" ,
        "يكمل العمل على مستوى تقني عالي" ,
        "المتابعة واتخاذ الإجراءات عندما لا تتحقق الأهداف لضمان نتائج أفضل في المستقبل." ,
        "وضع معايير عالية في أدائهم" ,
        "يحقق الأهداف في الموعد المحدد وفي ظل الميزانية." ,
    ] ,
    "التحيز للعمل" => [
        "ينم عن إلحاح الحاجة إلى معالجة المشاكل والفرص" ,
        "تحديد طرق تبسيط إجراءات العمل وتقليل أوقات الدورات" ,
        "يهتم بإنجاز الأمور في الوقت المحدد وفي حدود الميزانية" ,
        "يحفز الآخرين بشكل إيجابي على تحقيق الأهداف أو تجاوزها" ,
        "يستجيب بسرعة لقضايا الأشخاص الصعبة عند التعامل مع العملاء الداخليين أو الخارجيين.",
    ] ,
    "إدارة التغيير" => [
        "يدعم جهود الشركة لتنفيذ التغييرات.",
        "يعالج المقاومة التنظيمية والإدارية للتغييرات." ,
        "تنفذ إجراءات لتخطيط وإدارة التغييرات." ,
        "يساعد القسم في إدارة التغييرات التنظيمية.",
        "يعمل بشكل تعاوني مع الآخرين لتنفيذ التغييرات." ,
    ] ,
    "اتخاذ القرار" => [
        "تحديد مواضع اختلاف النتائج الفعلية عن النتائج المرغوبة وإجراء التصحيحات اللازمة" ,
        "لا يغيب عن بالنا الصورة الكبيرة عند اتخاذ القرارات" ,
        "يفهم القضايا والمشاكل والحلول المحتملة." ,
        "يمارس الحكم الصائب من خلال اتخاذ قرارات سليمة ومستنيرة." ,
        "يبقى هادئًا عند اتخاذ قرارات مهمة أو صعبة." ,
    ] ,
    "تطوير الآخرين" => [
        "تخلق بيئة عمل تعزز ردود الفعل الإيجابية للموظفين." ,
        "يعزز معرفة ومهارات الآخرين." ,
        "يقدم ملاحظات بناءة للآخرين." ,
        "يستخدم الزيارات المخطط لها وغير المخطط لها كفرص للتدريب." ,
        "يساعد المرؤوسين في بناء خطط التنمية الفردية" ,
    ] ,
    "تمكين الآخرين" => [
        "يشجع الموظفين على حل المشكلات بأنفسهم" ,
        "يسمح للأفراد بأن يكونوا مسؤولين عن قراراتهم" ,
        "يشجع الآخرين على اكتساب المهارات والتدريب اللازمين" ,
        "يشجع الآخرين على تجاوز أهدافهم المعلنة" ,
        "يطلب مدخلات من الآخرين لاتخاذ قرارات مستنيرة." ,
    ] ,
    "إنشاء التركيز / الاتجاه" => [
        "يبقى مركزًا حتى تحت الضغط والتوتر." ,
        "ممتاز في إدارة الوقت.",
        "العمل بشكل جيد تحت الضغط , والمواعيد النهائية , و / أو أعباء العمل الكبيرة." ,
        "يحافظ على ضبط النفس عند انتقاده شخصيًا" ,
        "يوفق بين الموظفين لتلبية احتياجات واهتمامات العملاء." ,
    ] ,
    "التميز" => [
        "يمكن الاعتماد عليها لإضافة قيمة أينما كانوا." ,
        "يوضح المهارات التحليلية للقيام بعملهم." ,
        "ينتج عملًا عالي الجودة.",
        "يفخر بعملهم كثيرًا" ,
        "يستخدم العمليات للحصول على نتائج متسقة.",
    ] ,
    "المرونة" => [
        "يتكيف مع الإجراءات الجديدة." ,
        "فعالة في دمج الأفكار الجديدة." ,
        "منفتح على طرق بديلة لتحقيق الأهداف" ,
        "يعمل بشكل فعال خلال فترات التغيير" ,
        "قادرة على إجراء تغييرات في منتصف الطريق في المهام أو المشاريع الحالية." ,
    ] ,
    "الأهداف" => [
        "يحقق الأهداف المحددة" ,
        "يحدد ويوثق الغايات والأهداف" ,
        "تأكد من أن أعضاء الفريق لديهم فكرة واضحة عن أهداف مجموعتنا." ,
        "يضع أهدافًا قصيرة وطويلة المدى لنفسك دون أن تدفعها." ,
        "يضعون أهدافًا لأنفسهم بشكل احترافي." ,
    ] ,
    "المبادرة" => [
        "درب الآخرين على تعزيز بيئة يمكنها التكيف بسرعة وبإرادة للتغير السريع." ,
        "يتجاوز الأهداف المعلنة." ,
        "يتخذ إجراء دون أن يطلب منه ذلك" ,
        "يأخذ زمام المبادرة لتغيير اتجاه أو مسار الأحداث." ,
        "يعمل على الفور لإكمال الأهداف قبل وقت طويل من الموعد النهائي لها.",
    ] ,
    "الابتكار" => [
        "يقترح أفكارًا جديدة في الاجتماعات" ,
        "يخلق عمليات جديدة وفعالة.",
        "يطور العديد من الأساليب أو الحلول لمشكلة ما." ,
        "تعظيم الحلول البديلة للمشاكل." ,
        "يبحث عن فرص لتطبيق التقنيات الجديدة والمتطورة." ,
    ] ,
    "النزاهة" => [
        "تعزز بيئة مبنية على الثقة." ,
        "هل ما وعدت" ,
        "يحمي سلامة وسرية المعلومات.",
        "قادرة على الحفاظ على سرية المعلومات." ,
        "يؤسس علاقات الثقة والصدق والإنصاف والنزاهة." ,
    ]
];

$en =  [
    "Accountability" => [
        "Is aware of problems or issues that may affect the organization.",
        "Defines roles, rights, and responsibilities of employees.",
        "Takes responsibility for results.",
        "Encourages employees to set challenging but achievable goals.",
        "Accepts accountability for results.",
    ],
    "Achievement" => [
        "Accepts setbacks and challenges as improvement opportunities",
        "Completes work to a high technical standard",
        "Follows-up and takes action when goals are not met to ensure better results in the future.",
        "Set high standards in their performance",
        "Accomplishes goals on schedule and under budget.",
    ],
    "Bias for Action" => [
        "Conveys a sense of urgency about addressing problems and opportunities",
        "Identifies ways to simplify work processes and reduce cycle times",
        "Is concerned about getting things done on time and within budget",
        "Positively motivates others to achieve or exceed goals",
        "Responds quickly to tough \"people issues\" when dealing with internal or external customers.",
    ],
    "Change Management" => [
        "Supports Company's efforts to implement changes.",
        "Addresses organizational and departmental resistance to changes.",
        "Implements procedures to plan and manage changes.",
        "Helps the department manage organizational changes.",
        "Works cooperatively with others to implement changes.",
    ],
    "Decision Making" => [
        "Determines where actual results differ from desired results and makes necessary corrections",
        "Does not lose sight of the big picture when making decisions",
        "Understands the issues, problems, and potential solutions.",
        "Exercises good judgment by making sound and informed decisions.",
        "Remains calm when making important or difficult decisions.",
    ],
    "Developing Others" => [
        "Creates an work environment that fosters positive feedback to employees.",
        "Enhances the knowledge and skills of others.",
        "Provides constructive feedback to others.",
        "Uses planned and unplanned visits as opportunities to train.",
        "Helps subordinates in building Individual Development Plans.",
    ],
    "Empowering Others" => [
        "Encourages employees to solve problems on their own.",
        "Allows individuals to be responsible for their decisions.",
        "Encourages others to obtain necessary skills and training.",
        "Encourages others to exceed their stated goals.",
        "Solicits input from others to make informed decisions.",
    ],
    "Establishing Focus / Direction" => [
        "Stays focused even when under pressure and stress.",
        "Excellent at managing time.",
        "Function well under stress, deadlines, and/or significant workloads.",
        "Maintains self-control when personally criticized.",
        "Aligns employees to address needs and concerns of customers.",
    ],
    "Excellence" => [
        "Can be counted on to add value wherever they are involved.",
        "Demonstrates the analytical skills to do their job.",
        "Produces high quality work.",
        "Takes a lot of pride in their work.",
        "Uses processes to get consistent results.",
    ],
    "Flexibility" => [
        "Adapts to new procedures.",
        "Effective in incorporating new ideas.",
        "Is open to alternative ways to accomplish goals",
        "Works effectively during periods of change.",
        "Able to make changes midstream into current tasks or projects.",
    ],
    "Goals" => [
        "Achieves established goals.",
        "Establishes and documents goals and objectives.",
        "Makes sure that team members have a clear idea of our group's goals.",
        "Sets short and long term goals for self without being pushed.",
        "Sets goals for themselves professionally.",
    ],
    "Initiative" => [
        "Coach others to foster an environment which can adapt quickly and willingly to rapid change.",
        "Goes above and beyond the stated goals.",
        "Takes action without being asked.",
        "Takes the initiative to change the direction or course of events.",
        "Immediately works to complete goals well before their deadline.",
    ],
    "Innovation" => [
        "Suggests new ideas at meetings.",
        "Creates new and efficient processes.",
        "Develops several approaches or solutions to a problem.",
        "Maximizes the alternative solutions to problems.",
        "Looks for opportunities to apply new and evolving technologies.",
    ],
    "Integrity" => [
        "Fosters an environment built upon trust.",
        "Does what was promised.",
        "Protects the integrity and confidentiality of information.",
        "Able to maintain confidential information.",
        "Establishes relationships of trust, honesty, fairness, and integrity.",
    ],
    "Interpersonal Skills" => [
        "Successfully resolves conflicts and grievances to a win-win solution.",
        "Adapts management style to meet the needs of the individual or situation.",
        "Demonstrates compassion and understanding of others.",
        "Establishes good rapport with employees and customers.",
    ],
    "Managing Performance" => [
        "Addresses grievances sooner rather than later.",
        "Measures performance against goals and objectives.",
        "Reviews job performance shortly after completion of tasks.",
        "Rewards employees for exceeding goals.",
        "Sets challenging goals and objectives.",
    ],
    "Problem Solving" => [
        "Able to solve problems at root cause rather than at symptom level.",
        "Asks the \"right\" questions to size up or evaluate situations.",
        "Determines the impact of recommended solutions.",
        "Makes judgments based upon relevant information.",
        "Solves problems that have difficult or conflicting constraints.",
    ],
    "Professional Development" => [
        "Demonstrate enthusiasm and a willingness to learn new skills and knowledge",
        "Quickly acquire and apply new knowledge and skills when needed",
        "Allows employees to fully participate in employee training and professional development.",
        "Seeks opportunities for professional development.",
        "Encourages employees to advance their education.",
    ],
    "Project Management" => [
        "Works with customers and clients to assess their needs and define project parameters.",
        "Develops and maintains strong relationships with suppliers and contractors.",
        "Organizes work and sets priorities as needed.",
        "Able to coordinate interdependent phases of projects.",
        "Coordinates the activities of various teams and departments.",
    ],
    "Teamwork" => [
        "Actively participates as a team member",
        "Coaches team on how to solve problems, plan, and meet organizational goals and objectives.",
        "Encourages teamwork and collaboration.",
        "Provides assistance and support to other team members when needed.",
        "Recognizes the contributions of the team.",
    ],
];

return $ar;
